import React, { useState } from 'react';
import { View, Text, StyleSheet, TouchableOpacity, ScrollView, Alert, ActivityIndicator, Platform } from 'react-native';
import { Colors, Shadows } from '../styles';
import RemedyResultCard from '../components/RemedyResultCard';
import { saveCase } from '../services/api';

export default function RemedyResultsScreen({ route, navigation }: any) {
  const { remedies, confirmedRubrics, analysisSummary } = route.params || {};
  const [isSaving, setIsSaving] = useState(false);

  async function handleFinalize() {
    setIsSaving(true);
    try {
      // Create a professional title from the first rubric or summary
      const caseTitle = analysisSummary 
        ? (analysisSummary.length > 30 ? analysisSummary.substring(0, 30) + "..." : analysisSummary)
        : (confirmedRubrics?.[0] || "New Clinical Case");

      await saveCase({
        name: caseTitle,
        initials: "AI",
        specialty: "Clinical CDSS Case",
        time: new Date().toLocaleString([], { hour: '2-digit', minute: '2-digit', hour12: true }).toUpperCase(),
        summary: analysisSummary,
        rubrics: confirmedRubrics,
        remedies: remedies
      });

      if (Platform.OS === 'web') {
        window.alert("Case Finalized! ✅\nThe analysis and matched remedies have been saved to your clinical history.");
        navigation.navigate('Cases');
      } else {
        Alert.alert(
          "Case Finalized! ✅",
          "The analysis and matched remedies have been saved to your clinical history.",
          [{ text: "Back to Home", onPress: () => navigation.navigate('Cases') }]
        );
      }
    } catch (error) {
      console.error("Save failed", error);
      Alert.alert("Save Failed", "Could not save the case. Please check your connection.");
    } finally {
      setIsSaving(false);
    }
  }

  return (
    <ScrollView style={styles.container} showsVerticalScrollIndicator={false}>
      <View style={styles.content}>
        {/* Header */}
        <View style={styles.header}>
          <Text style={styles.headerTitle}>Remedy Decision Support</Text>
          <Text style={styles.headerSubtitle}>Phase 3: Ranked clinical suggestions</Text>
        </View>

        {/* Confirmed Rubrics Recap */}
        <View style={styles.recapCard}>
          {analysisSummary && (
            <View style={styles.summaryWrapper}>
              <Text style={styles.summaryTitle}>CASE SUMMARY:</Text>
              <Text style={styles.summaryText}>{analysisSummary}</Text>
            </View>
          )}
          <Text style={styles.recapTitle}>Confirmed Basis:</Text>
          <View style={styles.tagContainer}>
            {confirmedRubrics?.map((path: string, i: number) => (
              <View key={i} style={styles.tag}>
                <Text style={styles.tagText}>{path}</Text>
              </View>
            ))}
          </View>
        </View>

        {/* Decision Support Notice */}
        <View style={[styles.noticeCard, Shadows.small]}>
          <Text style={styles.noticeTitle}>NOTICE: SUPPORTIVE DATA ONLY</Text>
          <Text style={styles.noticeText}>
            These results are generated by the Reperto Core medical engine based on the confirmed rubrics. They do not constitute a diagnosis.
          </Text>
        </View>

        {/* Results Section */}
        <View style={styles.resultsSection}>
          <Text style={styles.sectionTitle}>RANKED REMEDIES</Text>
          
          {remedies && remedies.length > 0 ? (
            remedies.map((item: any, index: number) => (
              <RemedyResultCard
                key={index}
                rank={index + 1}
                remedyName={item.remedy}
                score={item.score}
                rationale={item.rationale}
                contributions={item.rubrics || []}
              />
            ))
          ) : (
            <View style={styles.emptyState}>
              <Text style={styles.emptyText}>No matching remedies found for these rubrics.</Text>
            </View>
          )}
        </View>

        {/* Action Buttons */}
        <View style={styles.actionRow}>
          <TouchableOpacity
            style={[styles.actionBtn, styles.primaryBtn, isSaving && { opacity: 0.7 }]}
            onPress={handleFinalize}
            disabled={isSaving}
          >
            {isSaving ? (
              <ActivityIndicator color="#fff" />
            ) : (
              <Text style={styles.primaryBtnText}>Finalize and Save Case</Text>
            )}
          </TouchableOpacity>
          
          <TouchableOpacity
            style={[styles.actionBtn, styles.secondaryBtn]}
            onPress={() => navigation.goBack()}
          >
            <Text style={styles.secondaryBtnText}>Back to Review</Text>
          </TouchableOpacity>
        </View>
      </View>
    </ScrollView>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Colors.background,
  },
  content: {
    padding: 20,
    paddingBottom: 60,
  },
  header: {
    marginBottom: 24,
  },
  headerTitle: {
    fontSize: 22,
    fontWeight: '700',
    color: Colors.text,
  },
  headerSubtitle: {
    fontSize: 14,
    color: Colors.success,
    fontWeight: '500',
    marginTop: 4,
  },
  recapCard: {
    backgroundColor: Colors.lightGray,
    borderRadius: 12,
    padding: 16,
    marginBottom: 20,
  },
  recapTitle: {
    fontSize: 11,
    fontWeight: '700',
    color: Colors.textSecondary,
    marginBottom: 10,
    textTransform: 'uppercase',
  },
  tagContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
  },
  tag: {
    backgroundColor: Colors.background,
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 6,
    marginRight: 6,
    marginBottom: 6,
    borderWidth: 1,
    borderColor: Colors.border,
  },
  tagText: {
    fontSize: 12,
    color: Colors.text,
  },
  summaryWrapper: {
    marginBottom: 16,
    paddingBottom: 16,
    borderBottomWidth: 1,
    borderBottomColor: Colors.border,
  },
  summaryTitle: {
    fontSize: 10,
    fontWeight: '800',
    color: Colors.textSecondary,
    marginBottom: 4,
  },
  summaryText: {
    fontSize: 13,
    color: Colors.text,
    lineHeight: 18,
    fontStyle: 'italic',
  },
  noticeCard: {
    backgroundColor: Colors.orangeBadge,
    borderRadius: 12,
    padding: 16,
    marginBottom: 24,
    borderLeftWidth: 4,
    borderLeftColor: Colors.warning,
  },
  noticeTitle: {
    fontSize: 12,
    fontWeight: '800',
    color: Colors.orangeText,
    marginBottom: 4,
  },
  noticeText: {
    fontSize: 12,
    color: Colors.orangeText,
    lineHeight: 18,
    opacity: 0.9,
  },
  resultsSection: {
    marginBottom: 30,
  },
  sectionTitle: {
    fontSize: 12,
    fontWeight: '700',
    color: Colors.textLight,
    letterSpacing: 1,
    marginBottom: 16,
  },
  emptyState: {
    padding: 40,
    alignItems: 'center',
  },
  emptyText: {
    color: Colors.textLight,
    textAlign: 'center',
  },
  actionRow: {
    gap: 12,
  },
  actionBtn: {
    height: 52,
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
  },
  primaryBtn: {
    backgroundColor: Colors.primary,
  },
  primaryBtnText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '700',
  },
  secondaryBtn: {
    backgroundColor: Colors.background,
    borderWidth: 1.5,
    borderColor: Colors.border,
  },
  secondaryBtnText: {
    color: Colors.textSecondary,
    fontSize: 15,
    fontWeight: '600',
  },
});
